Repository tjarbo/discord-moodle-bot, pull requests merged in 2020-06, with the labels that each got.

#6 Improve authentification using jwt
  packages/backend/src/controllers/authentication/auth.ts
  packages/backend/src/routes/authentication.routes.ts
  packages/backend/tests/auth.spec.ts
  packages/frontend/src/App.vue
  packages/frontend/src/store/index.js
  packages/frontend/src/store/utils/StoreUtil.js
  packages/frontend/src/views/Login.vue
  packages/frontend/tests/unit/login.view.spec.js
Labels: :butterfly: bugfix

#7 Set moodle refresh rate
  packages/backend/index.ts
  packages/backend/src/controllers/refreshRate/refreshRate.schema.ts
  packages/backend/src/controllers/refreshRate/refreshRate.ts
  packages/backend/src/routes/index.routes.ts
  packages/backend/src/routes/settings.routes.ts
  packages/frontend/src/components/RefreshRateInput.vue
  packages/frontend/src/router/index.js
  packages/frontend/src/store/index.js
  packages/frontend/src/views/Dashboard.vue
Labels: :eyeglasses: Need review, :sparkles: enhancement

#5 Logout Method
  packages/frontend/src/App.vue
  packages/frontend/src/components/NavBar.vue
  packages/frontend/src/router/index.js
  packages/frontend/src/store/index.js
  packages/frontend/src/views/Dashboard.vue
  packages/frontend/tests/unit/dashboard.view.spec.js
  packages/frontend/tests/unit/navbar.spec.js
Labels: :eyeglasses: Need review, :sparkles: enhancement

#8 Set course list
  packages/backend/package-lock.json
  packages/backend/src/controllers/courseList/courseList.schema.ts
  packages/backend/src/controllers/courseList/courseList.ts
  packages/backend/src/controllers/moodle/index.ts
  packages/backend/src/routes/settings.routes.ts
  packages/frontend/src/components/CourseSelection.vue
  packages/frontend/src/store/index.js
  packages/frontend/src/views/Dashboard.vue
Labels: :eyeglasses: Need review, :sparkles: enhancement

#9 Set discord channel
  README.md
  packages/backend/src/controllers/discord/index.ts
  packages/backend/src/controllers/discordChannel/discordChannel.schema.ts
  packages/backend/src/controllers/discordChannel/discordChannel.ts
  packages/backend/src/routes/settings.routes.ts
  packages/frontend/src/components/DiscordChannelInput.vue
  packages/frontend/src/store/index.js
  packages/frontend/src/views/Dashboard.vue
Labels: :eyeglasses: Need review, :sparkles: enhancement

#10 Add administrator
  packages/backend/index.ts
  packages/backend/src/configuration/environment.ts
  packages/backend/src/controllers/administrator/administrator.schema.ts
  packages/backend/src/controllers/administrator/index.ts
  packages/backend/src/controllers/authentication/auth.ts
  packages/backend/src/docs/rest-api.yml
  packages/backend/src/routes/settings.routes.ts
  packages/backend/tests/administrator.spec.ts
  packages/backend/tests/auth.spec.ts
  packages/backend/tests/discord.spec.ts
  packages/backend/tests/moodle.fetch.spec.ts
  packages/backend/tests/moodle.spec.ts
  packages/frontend/src/components/AddAdministrator.vue
  packages/frontend/src/store/index.js
  packages/frontend/src/views/Dashboard.vue
  packages/frontend/tests/unit/dashboard.view.spec.js
Labels: :eyeglasses: Need review, :sparkles: enhancement

#22 Fix moodle fetch
  packages/backend/src/controllers/moodle/fetch.ts
  packages/backend/src/controllers/moodle/handle.ts
  packages/backend/src/controllers/moodle/index.ts
  packages/backend/tests/moodle.handle.spec.ts
  packages/backend/tests/moodle.spec.ts
  packages/frontend/vue.config.js
Labels: :butterfly: bugfix, :eyeglasses: Need review

#25 :bug: Fixed duplicate message workaround
  packages/backend/src/controllers/moodle/handle.ts
Labels: :butterfly: bugfix, :eyeglasses: Need review

#27 :twisted_rightwards_arrows: Added api documentation (#2)
  packages/backend/src/docs/rest-api.yml
Labels: :eyeglasses: Need review, :memo: documentation

#33 🎨 Bulma CSS für die Anmeldung
  .github/workflows/node.js.yml
  packages/backend/src/controllers/authentication/auth.ts
  packages/frontend/package-lock.json
  packages/frontend/package.json
  packages/frontend/public/index.html
  packages/frontend/src/main.js
  packages/frontend/src/store/index.js
  packages/frontend/src/store/utils/StoreUtil.js
  packages/frontend/src/views/Login.vue
  packages/frontend/tests/unit/login.view.spec.js
Labels: :eyeglasses: Need review, ⚡️ Improvement
