Repository tjarbo/discord-moodle-bot, pull requests merged in 2020-07, with the labels that each got.

#35 Doppelter Aufruf von fetch-Methoden entfernt
  packages/backend/src/controllers/discord/templates/index.ts
  packages/backend/src/controllers/discord/templates/resourceMessage.class.ts
  packages/backend/src/controllers/moodle/fetch.ts
  packages/backend/src/controllers/moodle/handle.ts
  packages/backend/src/controllers/moodle/index.ts
  packages/backend/src/controllers/moodle/interfaces/resource.interface.ts
  packages/backend/tests/auth.spec.ts
  packages/backend/tests/moodle.fetch.spec.ts
  packages/backend/tests/moodle.handle.spec.ts
  packages/backend/tests/moodle.spec.ts
Labels: :butterfly: bugfix, :eyeglasses: Need review

#40 Fixed ignored refreshRate modifications
  packages/backend/index.ts
  packages/backend/src/controllers/moodle/index.ts
Labels: :butterfly: bugfix, :eyeglasses: need review

#37 🎨 Bulma CSS für das Dashboard
  README.md
  packages/frontend/.eslintrc.js
  packages/frontend/package-lock.json
  packages/frontend/package.json
  packages/frontend/src/components/AddAdministrator.vue
  packages/frontend/src/components/CourseSelection.vue
  packages/frontend/src/components/DiscordChannelInput.vue
  packages/frontend/src/components/NavBar.vue
  packages/frontend/src/components/RefreshRateInput.vue
  packages/frontend/src/components/TheNavBar.vue
  packages/frontend/src/components/administration/AddAdministrator.vue
  packages/frontend/src/components/discord/DiscordPanel.vue
  packages/frontend/src/components/moodle/SetCourseNotifications.vue
  packages/frontend/src/components/moodle/SetRefreshRate.vue
  packages/frontend/src/fmdb.scss
  packages/frontend/src/main.js
  packages/frontend/src/store/index.js
  packages/frontend/src/views/Dashboard.vue
  packages/frontend/src/views/Login.vue
  packages/frontend/tests/unit/TheNavBar.component.spec.js
  packages/frontend/tests/unit/administration/AddAdministrator.component.spec.js
  packages/frontend/tests/unit/bots/DiscordPanel.component.spec.js
  packages/frontend/tests/unit/dashboard.view.spec.js
  packages/frontend/tests/unit/moodle/SetCourseNotifications.component.spec.js
  packages/frontend/tests/unit/moodle/SetRefreshRate.component.spec.js
  packages/frontend/tests/unit/navbar.spec.js
  packages/frontend/tests/unit/views/dashboard.view.spec.js
  packages/frontend/tests/unit/views/login.view.spec.js
Labels: :eyeglasses: need review, ⚡️ improvement

#43 🐛 Fixes #42 and #21
  packages/frontend/src/App.vue
  packages/frontend/src/store/index.js
  packages/frontend/src/views/Login.vue
  packages/frontend/tests/unit/views/login.view.spec.js
Labels: :butterfly: bugfix, :eyeglasses: need review
