Repository tjarbo/discord-moodle-bot, pull requests merged in 2020-10, with the labels that each got.

#54 :sparkles: Added tool to generate token and moodle environment variables
  docs/CNAME
  docs/FMDB_logo.png
  docs/index.html
  docs/main.js
  docs/style.css
Labels: :eyeglasses: need review, ⚡️ improvement

#52 Feature/issue 18
  packages/backend/index.ts
  packages/backend/src/controllers/administrator/administrator.schema.ts
  packages/backend/src/controllers/administrator/index.ts
  packages/backend/src/docs/rest-api.yml
  packages/backend/src/routes/settings.routes.ts
  packages/backend/tests/administrator.spec.ts
  packages/frontend/src/components/administration/AddAdministrator.vue
  packages/frontend/src/components/administration/AdministratorList.vue
  packages/frontend/src/store/modules/administration.js
  packages/frontend/src/views/Dashboard.vue
  packages/frontend/tests/unit/administration/AddAdministrator.component.spec.js
  packages/frontend/tests/unit/administration/AdministratorList.component.spec.js
Labels: :sparkles: new feature

#61 Feature/issue 58
  package-lock.json
  packages/backend/index.ts
  packages/backend/src/controllers/moodle/index.ts
  packages/backend/src/controllers/moodle/refreshRate.ts
  packages/backend/src/controllers/moodle/schemas/lastfetch.schema.ts
  packages/backend/src/controllers/moodle/schemas/moodle.schema.ts
  packages/backend/src/controllers/refreshRate/refreshRate.schema.ts
  packages/backend/src/controllers/status/status.ts
  packages/backend/src/docs/rest-api.yml
  packages/backend/src/routes/index.routes.ts
  packages/backend/src/routes/settings.routes.ts
  packages/backend/tests/moodle.spec.ts
  packages/frontend/src/components/statusboard/Status.vue
  packages/frontend/src/store/modules/moodle.js
Labels: :eyeglasses: need review
