Repository tjarbo/discord-moodle-bot, pull requests merged in 2020-05, with the labels that each got.

#1 User login
  .gitignore
  README.md
  package-lock.json
  package.json
  packages/backend/README.md
  packages/backend/index.ts
  packages/backend/jest.config.js
  packages/backend/package-lock.json
  packages/backend/package.json
  packages/backend/src/configuration/discord.ts
  packages/backend/src/configuration/environment.ts
  packages/backend/src/configuration/express.ts
  packages/backend/src/configuration/logger.ts
  packages/backend/src/controllers/.gitkeep
  packages/backend/src/controllers/authentication/auth.ts
  packages/backend/src/controllers/authentication/token.schema.ts
  packages/backend/src/controllers/error/api.class.ts
  packages/backend/src/controllers/error/handler.ts
  packages/backend/src/controllers/user/user.schema.ts
  packages/backend/src/docs/rest-api.json
  packages/backend/src/docs/rest-api.yml
  packages/backend/src/missing_types.ts
  packages/backend/src/routes/authentication.routes.ts
  packages/backend/src/routes/documentation.routes.ts
  packages/backend/src/routes/index.routes.ts
  packages/backend/tests/auth.spec.ts
  packages/backend/tsconfig.json
  packages/backend/tsconfig.spec.json
  packages/backend/tslint.json
  packages/frontend/.eslintrc.js
  packages/frontend/package-lock.json
  packages/frontend/package.json
  packages/frontend/public/index.html
  packages/frontend/src/App.vue
  packages/frontend/src/assets/FMDB_logo.png
  packages/frontend/src/main.js
  packages/frontend/src/router/index.js
  packages/frontend/src/store/index.js
  packages/frontend/src/store/utils/StoreUtil.js
  packages/frontend/src/views/About.vue
  packages/frontend/src/views/Home.vue
  packages/frontend/src/views/Login.vue
  packages/frontend/tests/unit/example.spec_.js
  packages/frontend/tests/unit/login.view.spec.js
Labels: enhancement

#3 Unit Tests 1
  packages/backend/index.ts
  packages/backend/src/configuration/__mocks__/discord.ts
  packages/backend/src/configuration/__mocks__/environment.ts
  packages/backend/tests/auth.spec.ts
Labels: :butterfly: bugfix

#4 Discord sendTo and publish Methods
  README.md
  packages/backend/src/configuration/__mocks__/discord.ts
  packages/backend/src/configuration/environment.ts
  packages/backend/src/controllers/authentication/auth.ts
  packages/backend/src/controllers/discord/index.ts
  packages/backend/src/controllers/discord/message.class.ts
  packages/backend/src/controllers/discord/message.interface.ts
  packages/backend/src/controllers/discord/templates/assignmentMessage.class.ts
  packages/backend/src/controllers/discord/templates/assignmentReminderMessage.class.ts
  packages/backend/src/controllers/discord/templates/index.ts
  packages/backend/src/controllers/discord/templates/ressourceMessage.class.ts
  packages/backend/src/controllers/discord/templates/tokenRequestMessage.class.ts
  packages/backend/src/controllers/error/handler.ts
  packages/backend/tests/auth.spec.ts
  packages/backend/tests/discord.spec.ts
  packages/backend/tests/error.handler.spec.ts
  packages/backend/tsconfig.json
  packages/backend/tsconfig.spec.json
  packages/backend/tslint.json
Labels: :eyeglasses: Need review, :sparkles: enhancement

#2 Moodle fetch
  .gitignore
  README.md
  package-lock.json
  packages/backend/index.ts
  packages/backend/package-lock.json
  packages/backend/package.json
  packages/backend/src/configuration/__mocks__/environment.ts
  packages/backend/src/configuration/environment.ts
  packages/backend/src/controllers/discord/templates/assignmentMessage.class.ts
  packages/backend/src/controllers/discord/templates/assignmentReminderMessage.class.ts
  packages/backend/src/controllers/discord/templates/ressourceMessage.class.ts
  packages/backend/src/controllers/moodle/fetch.ts
  packages/backend/src/controllers/moodle/handle.ts
  packages/backend/src/controllers/moodle/index.ts
  packages/backend/src/controllers/moodle/interfaces/assignment.interface.ts
  packages/backend/src/controllers/moodle/interfaces/config.interface.ts
  packages/backend/src/controllers/moodle/interfaces/contentfile.interface.ts
  packages/backend/src/controllers/moodle/interfaces/course.interface.ts
  packages/backend/src/controllers/moodle/interfaces/coursedetails.interface.ts
  packages/backend/src/controllers/moodle/interfaces/ressource.interface.ts
  packages/backend/src/controllers/moodle/schemas/lastfetch.schema.ts
  packages/backend/src/controllers/moodle/schemas/reminder.schema.ts
  packages/backend/tests/moodle.fetch.spec.ts
  packages/backend/tests/moodle.handle.spec.ts
  packages/backend/tests/moodle.spec.ts
  packages/backend/tsconfig.json
Labels: :eyeglasses: Need review, :sparkles: enhancement
