Repository tjarbo/discord-moodle-bot, pull requests merged in 2021-04, with the labels that each got.

#106 🔀 Provide default value for timestamp. Fixes #60
  packages/backend/src/controllers/moodle/handle.ts
  packages/backend/tests/moodle.handle.spec.ts
Labels: :butterfly: bugfix

#109 🔀 Added Administrator Management based on registration tokens
  packages/backend/index.ts
  packages/backend/src/controllers/administrator/administrator.schema.ts
  packages/backend/src/controllers/administrator/authenticator.schema.ts
  packages/backend/src/controllers/administrator/index.ts
  packages/backend/src/controllers/authentication/index.ts
  packages/backend/src/controllers/authentication/registrationToken.schema.ts
  packages/backend/src/routes/settings.routes.ts
  packages/backend/tests/administrator.spec.off.ts
  packages/backend/tests/administrator.spec.ts
  packages/backend/tests/auth.spec.ts
  packages/frontend/package-lock.json
  packages/frontend/package.json
  packages/frontend/src/components/administration/AdministratorList.vue
  packages/frontend/src/components/administration/RegistrationTokenModal.vue
  packages/frontend/src/main.js
  packages/frontend/src/store/index.js
  packages/frontend/src/store/modules/administration.js
  packages/frontend/src/store/utils/StoreUtil.js
  packages/frontend/src/views/Dashboard.vue
  packages/frontend/src/views/Login.vue
  packages/frontend/src/views/Registration.vue
  packages/frontend/tests/unit/administration/AdministratorList.component.spec.js
  packages/frontend/tests/unit/views/registration.view.spec.js
Labels: :sparkles: new feature

#110 📝 Updated README - Fixes #107
  README.md
Labels: :eyeglasses: need review
